name: build.yml
on:
  push:
    branch: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add dist/index.js
          git add action.yml
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update workflow"
          git push origin HEAD:v1
